package io.github.xstefanox.underkow.test

internal class AnotherException : Exception()
